/*
 * commands.inc
 *
 *  Created: 27.12.2022 17:59:26
 *   Author: Mintytail
 */ 

 #define cbBrightnessUp 0x18
 #define cbBrightnessDown 0x17
 #define cbOff 0x16
 #define cbOn 0x15
 #define cbR4 0x14
 #define cbG4 0x13
 #define cbB4 0x12
 #define cbWhite 0x11
 #define cbR3 0x10
 #define cbG3 0x0F
 #define cbB3 0x0E
 #define cbFlash 0x0D
 #define cbR2 0x0C
 #define cbG2 0x0B
 #define cbB2 0x0A
 #define cbStrobe 0x09
 #define cbR1 0x08
 #define cbG1 0x07
 #define cbB1 0x06
 #define cbFade 0x05
 #define cbR0 0x04
 #define cbG0 0x03
 #define cbB0 0x02
 #define cbSmooth 0x01
